spring:
  application:
    name: company-fallback
server:
  port: ${PORT:9797}
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
